from . import product_template
from . import sale_order
from . import res_partner
from . import account_move
from . import purchase_order
from . import wizart
from . import sale_advance_payment_inv
from . import stock_picking
from . import res_company
